import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Login from "./login";
import test from "./test";
import Footerc from "./footer";
import PantallaCurso from "./msdocente";
import Curso from "./cursowindow";
import Link from "next/link";
import CreateUser from "./crearUsuario"
import VentanaJefe from "./AcademicChief/msjefe";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>SmartLearn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" defer></script>

      </Head>
      <Login></Login>     
      
      <VentanaJefe></VentanaJefe>

      
    
      
    </>
  );
}
